[changelog]
body = """

## æ’ä»¶æ›´æ–°
> [!NOTE]
> å½“å‰ç‰ˆæœ¬ï¼š`{% if version %}({{ version }}){%- endif -%}`

{% for group, commits in commits | group_by(attribute="group") %}

{% if group != "âœ¨ æ–°äº®ç‚¹" %}
<details>
<summary><h3>{{ group | upper_first }}</h3></summary>
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {%- endif -%}{{ commit.message | upper_first }}\
  {% if commit.remote.username %} ä½œè€…: @{{ commit.remote.username }}{%- endif -%}
{% endfor %}
</details>
{% else %}
### {{ group | upper_first }}
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {%- endif -%}{{ commit.message | upper_first }}\
  {% if commit.remote.username %} ä½œè€…: @{{ commit.remote.username }}{%- endif -%}
{% endfor %}
{% endif %}

{% endfor -%}

{% if version %}
  {% if previous.version %}
**å®Œæ•´ Changelog**: ç‰ˆæœ¬å¯¹æ¯” {{ previous.version }} â†’ {{ version }}
  {% endif %}
{% else -%}
  {% raw %}
{% endraw %}
{% endif %}

"""
trim = true
footer = "<!-- generated by git-cliff -->"
output = "CHANGELOG.md"


[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "âœ¨ æ–°äº®ç‚¹"},
    { message = "^fix", group = "ğŸ› ï¸ ä¿®å¤çš„é—®é¢˜"},
    { message = "^refactor", group = "ğŸ”ƒ åŠŸèƒ½é‡æ„"},
    { message = "^docs", group = "ğŸ“„ æ–‡æ¡£æ›´æ–°"},
    { message = "^style", group = "ğŸï¸ æ ·å¼ä¼˜åŒ–"},
]
protect_breaking_commits = false
filter_commits = true
topo_order = false
sort_commits = "oldest"
link_parsers = []
