[project]
name = "com-lao-shui-yiyan"
version = "2.0.0"
description = "每天分享一句话，激励大家学习。"
authors = [
    {name = "LaoShui"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["class-widgets-sdk"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"